name: lofi
channels:
  - bioconda
  - conda-forge
dependencies:
  - bakta=1.9.4
  - parallel
  - python=3.10.14
  - pip=24.3.1
  - snakemake=7.32.4
  - pip:
      - bcbio-gff==0.7.1
      - gdown==5.2.0
      - hmmlearn==0.3.3
      - lightgbm==4.5.0
      - wget==3.2